### ISSUE TITLE
worded answers do not work

### ISSUE THREAD

**Issue by JakeT23cool** [JakeT23cool/TATH#4]
i assumed the worded answers would have the same variable naming convention as the multiple choice, but alas they do not so i have to fix this!

**Comment by DASPELLER4** [comment]
![image](https://user-images.githubusercontent.com/51001942/191360404-ff42a559-3b4d-431e-9a8e-9144459b75e7.png)

**Comment by DASPELLER4** [comment]
- [ ] poop
- [ ] peep
- [ ] penor

**Comment by DASPELLER4** [comment]
> * [x]  poop
> 
>     * [ ]  peep
> 
>     * [x]  penor

peep is lost

**Comment by JakeT23cool** [comment]
Fixed as of Final Update
